### ISSUE TITLE
Phasmophobia buddy resize issue

### ISSUE THREAD

**Issue by HikaruJoestar** [JacobSolomonUCF/phasmophobia-buddy#1]
As shown in the GIF at the link below, when resizing the window the evidence buttons get re-arranged in two columns instead of three like on mobile, when doing so they seem to push the ghost list down without resizing it so the bottom end of the list is outside the viewport of the window.

https://imgur.com/a/oTUVBoZ

**Comment by JacobSolomonUCF** [comment]
I do see the bug now, thanks for the details. I'll get this patched!

**Comment by JacobSolomonUCF** [comment]
Should be resolved!
